/**
 * Shared types and constants.
 */

/** Provenance headers for auto-generated files. */
export const VERSION_PICKER_PROVENANCE = `// AUTO-GENERATED by cf-deploy — do not edit.\n// Source: https://github.com/joeblew999/cf-deploy/blob/main/web/version-picker.js\n\n`;
export const VERSIONS_JSON_PROVENANCE = "AUTO-GENERATED by cf-deploy — do not edit. https://github.com/joeblew999/cf-deploy";

export interface GitInfo {
  commitSha: string;
  commitFull: string;
  commitMessage: string;
  branch: string;
  commitUrl: string;
}

export interface Release {
  version: string;
  tag: string;
  date: string;
  versionId: string;
  url: string; // alias URL (e.g. v0-7-0-myapp...) — latest upload for this tag
  previewUrl: string; // immutable URL (e.g. cf3bdf37-myapp...) — this exact upload
  healthy?: boolean;
  git?: GitInfo;
  commandCount?: number;
}

export interface Preview {
  label: string;
  tag: string;
  date: string;
  versionId: string;
  url: string;
  healthy?: boolean;
}

export interface VersionsJson {
  _provenance: string;
  production: string;
  github: string;
  generated: string;
  versions: Release[];
  previews: Preview[];
}
