/**
 * Wrangler execution helper, URL construction, version list parsing.
 */
import { execSync, type ExecSyncOptions } from "child_process";
import type { CfDeployConfig } from "./config.ts";
import versionPickerSource from "../web/version-picker.js" with { type: "text" };

// --- Version picker asset ---

export const VERSION_PICKER_JS =
  "// AUTO-GENERATED by cf-deploy — do not edit.\n// Source: https://github.com/joeblew999/cf-deploy/blob/main/web/version-picker.js\n\n" +
  versionPickerSource;

// --- URL construction ---

export function workerUrl(config: CfDeployConfig, prefix: string): string {
  return `https://${prefix}-${config.name}.${config.domain}`;
}

export function versionAliasUrl(
  config: CfDeployConfig,
  version: string,
): string {
  const slug = version.replaceAll(".", "-").toLowerCase();
  return workerUrl(config, `v${slug}`);
}

// --- Wrangler execution ---

export function wrangler(
  config: CfDeployConfig,
  args: string[],
  options: ExecSyncOptions = {},
) {
  const fullArgs = ["bun", "x", "wrangler", ...args, "--name", config.name];
  return execSync(fullArgs.map((a) => `"${a}"`).join(" "), {
    cwd: config.workerDir,
    stdio: "inherit",
    ...options,
  });
}

// --- Version list parsing ---

export interface WranglerVersion {
  versionId: string;
  created: string;
  tag: string;
}

export function fetchWranglerVersions(
  config: CfDeployConfig,
): WranglerVersion[] {
  const raw = wrangler(config, ["versions", "list"], {
    encoding: "utf8",
    stdio: ["pipe", "pipe", "pipe"],
  }).toString();
  return parseWranglerOutput(raw);
}

export function parseWranglerOutput(raw: string): WranglerVersion[] {
  const entries: WranglerVersion[] = [];
  let cur: Partial<WranglerVersion> = {};

  for (const line of raw.split("\n")) {
    const idMatch = line.match(/^Version ID:\s+(.+)/);
    const createdMatch = line.match(/^Created:\s+(.+)/);
    const tagMatch = line.match(/^Tag:\s+(.+)/);

    if (idMatch) {
      cur = { versionId: idMatch[1].trim() };
    } else if (createdMatch && cur.versionId) {
      cur.created = createdMatch[1].trim();
    } else if (tagMatch && cur.versionId) {
      cur.tag = tagMatch[1].trim();
      if (cur.tag !== "-" && cur.created) {
        entries.push(cur as WranglerVersion);
      }
      cur = {};
    }
  }
  return entries;
}
